
DROP DATABASE IF EXISTS climazon_db;
CREATE DATABASE climazon_db;
USE climazon_db;

CREATE TABLE planets (
    rowid INTEGER(4) NOT NULL,
    fpl_hostname VARCHAR(255),
    fpl_letter VARCHAR(255),
    fpl_name VARCHAR(255),
    fpl_discmethod VARCHAR(255),
    fpl_disc YEAR,
    fpl_orbper DECIMAL(10,4),
    fpl_orbperreflink VARCHAR(255),
    fpl_smax DECIMAL(10,4),
    fpl_smaxreflink VARCHAR(255),
    fpl_eccen DECIMAL(10,4),
    fpl_eccenreflink VARCHAR(255),
    fpl_bmasse DECIMAL(10,4),
    fpl_bmassj DECIMAL(10,4),
    fpl_bmassprov VARCHAR(255),
    fpl_bmassreflink VARCHAR(255),
    fpl_rade DECIMAL(10,4),
    fpl_radj DECIMAL(10,4),
    fpl_rads DECIMAL(10,4),
    fpl_radreflink VARCHAR(255),
    -- fpl_dens DECIMAL(10,4),
    -- fpl_densreflink VARCHAR(255),
    -- fpl_eqt DECIMAL(10,4),
    -- fpl_eqtreflink VARCHAR(255),
    -- fpl_insol DECIMAL(10,4),
    -- fpl_insolreflink VARCHAR(255),
    -- fpl_tranflag DECIMAL(10,4),
    -- fpl_cbflag DECIMAL(10,4),
    -- fpl_snum DECIMAL(10,4),
    -- ra_str VARCHAR(255),
    -- ra DECIMAL(20,10),
    -- dec_str DECIMAL(20,10),
    -- dec_ DECIMAL(20,10),
    -- fst_posreflink VARCHAR(255),
    -- fst_dist DECIMAL(10,4),
    -- fst_distreflink VARCHAR(255),
    -- fst_optmag DECIMAL(10,4),
    -- fst_optmagband VARCHAR(255),
    -- fst_optmagreflink VARCHAR(255),
    -- fst_nirmag DECIMAL(10,4),
    -- fst_nirmagband VARCHAR(255),
    -- fst_nirmagreflink VARCHAR(255),
    -- fst_spt VARCHAR(255),
    -- fst_sptreflink VARCHAR(255),
    -- fst_teff DECIMAL(10,4),
    -- fst_teffreflink VARCHAR(255),
    -- fst_logg DECIMAL(10,4),
    -- fst_loggreflink VARCHAR(255),
    -- fst_lum DECIMAL(10,4),
    -- fst_lumreflink VARCHAR(255),
    -- fst_mass DECIMAL(10,4),
    -- fst_massreflink VARCHAR(255),
    -- fst_rad DECIMAL(10,4),
    -- fst_radreflink VARCHAR(255),
    -- fst_met DECIMAL(10,4),
    -- fst_metratio VARCHAR(255),
    -- fst_metreflink VARCHAR(255),
    fst_age DECIMAL(10,4),
    -- fst_agereflink VARCHAR(255),
    PRIMARY KEY (rowid)
);

