
DROP DATABASE IF EXISTS climazon_db;
CREATE DATABASE climazon_db;
USE climazon_db;

CREATE TABLE inventory (
--     id INTEGER NOT NULL AUTO_INCREMENT,
--     item VARCHAR(40) NULL,
--     department VARCHAR(40),
--     price DECIMAL(20,2) NOT NULL,
--     stock INTEGER NOT NULL,
--     PRIMARY KEY (id)

-- );

    rowid INTEGER NOT NULL AUTO_INCREMENT,
    fpl_hostname VARCHAR(128),
    fpl_letter VARCHAR(128),
    fpl_name VARCHAR(128),
    fpl_discmethod VARCHAR(128),
    fpl_disc YEAR()
    -- fpl_orbper DECIMAL(10,4),
    -- fpl_orbperreflink VARCHAR(128),
    -- fpl_smax DECIMAL(10,4),
    -- fpl_smaxreflink VARCHAR(128),
    -- fpl_eccen DECIMAL(10,4),
    -- fpl_eccenreflink VARCHAR(128),
    -- fpl_bmasse DECIMAL(10,4),
    -- fpl_bmassj DECIMAL(10,4),
    -- fpl_bmassprov VARCHAR(128),
    -- fpl_bmassreflink VARCHAR(128),
    -- fpl_rade DECIMAL(10,4),
    -- fpl_radj DECIMAL(10,4),
    -- fpl_rads DECIMAL(10,4),
    -- fpl_radreflink VARCHAR(128),
    -- fpl_dens DECIMAL(10,4),
    -- fpl_densreflink VARCHAR(128),
    -- fpl_eqt DECIMAL(10,4),
    -- fpl_eqtreflink VARCHAR(128),
    -- fpl_insol DECIMAL(10,4),
    -- fpl_insolreflink VARCHAR(128),
    -- fpl_tranflag DECIMAL(10,4),
    -- fpl_cbflag DECIMAL(10,4),
    -- fpl_snum DECIMAL(10,4),
    -- ra_str VARCHAR(128),
    -- ra DECIMAL(20,10),
    -- dec_str DECIMAL(20,10),
    -- dec_ DECIMAL(20,10),
    -- fst_posreflink VARCHAR(128),
    -- fst_dist DECIMAL(10,4),
    -- fst_distreflink VARCHAR(128),
    -- fst_optmag DECIMAL(10,4),
    -- fst_optmagband VARCHAR(128),
    -- fst_optmagreflink VARCHAR(128),
    -- fst_nirmag DECIMAL(10,4),
    -- fst_nirmagband VARCHAR(128),
    -- fst_nirmagreflink VARCHAR(128),
    -- fst_spt VARCHAR(128),
    -- fst_sptreflink VARCHAR(128),
    -- fst_teff DECIMAL(10,4),
    -- fst_teffreflink VARCHAR(128),
    -- fst_logg DECIMAL(10,4),
    -- fst_loggreflink VARCHAR(128),
    -- fst_lum DECIMAL(10,4),
    -- fst_lumreflink VARCHAR(128),
    -- fst_mass DECIMAL(10,4),
    -- fst_massreflink VARCHAR(128),
    -- fst_rad DECIMAL(10,4),
    -- fst_radreflink VARCHAR(128),
    -- fst_met DECIMAL(10,4),
    -- fst_metratio VARCHAR(128),
    -- fst_metreflink VARCHAR(128),
    -- fst_age DECIMAL(10,4),
    -- fst_agereflink VARCHAR(128),
    PRIMARY KEY (rowid)

);
